language: python
python:
- '3.6'
install:
- make install-tests
script:
- make tests
deploy:
  provider: heroku
  app: movexplo
  api_key:
    secure: NpnUfyzPqH/b+dnvqFh6uJ6tSMrANgQmXjH1ewDqyxykQH3urCSaPszVU0AGaiOINvHs0ZJ5uPfy9cuzEvhvd4kY6VMRjAjA/1z8XzZhw1zBiqAOgAYZYsdvECO05ODCOpC9m+1TjABIt0xMXhb7kWI8L408FssdnjNiQu5QGrbzohJ0YAaPJhuDuCY7FXWyYzdr8KJpKeWGgsw7fs2YoftJX/1uRX/QlBF2rwk2r1+yPt6w64ZxzU0wBEBUqQnjpmvVwwmULVt2D7pIUlmEnB6XxTjHKhQ9Fy0+HAFbbTOzoyUfjHZsAjL9KtiBv/IQoRsRb5WQ+UZmRn2rGeuuH1osWkVLEOTI1nsVyQArE9XOL/YU1XeYYENrAHuchEpD1bQU/CcrHzYWACOTHUCXxNH7nxD9N3p41gGhNqSMxBbTxlQMgeWLpZciuTY2fGIPw/ba3mfEAHBrpxeDVIizFGdjNf6kpUYe4SPZsw6lg9AzibxAg4YSVjQmCKfHZTc+qQ0KwvmSd50LuMB4g71GNwMe2i1bHwhc1S++Z2wGQpIsg633UJzfqZK/cSaQvITuztkvaw2gP5mMHtyd+/F3J2s8sjTF87IK3SsHZRANmfudM+G9xFj5SDV6L7tfe2cOfZgdTpVKqknHzgyab8QtLs9HiJTCt7AbRgsEk7c2uJ0=
after_success:
- codecov -t $CODECOV_TOKEN
