language: python
python:
- '3.6'
install:
- make install
- make install-tests
script:
- make tests
deploy:
  provider: heroku
  app: movexplo
  api_key:
    secure: dhiypAzOjwFAs9U4CGYflgi6lbSZSCYTMwBvJojMV50WP1+NPTJE9WCPNM8297Q7e1iHArHll1LR0IYU8UbfwqDXj02utWagqxQJkGXNq5Z8aS9wgtm03qaduvg3cFBR8zsENRp07pljgpMUGi7NesanZKV6NLMzY9HFDYEXusRMoyTA8BhJsqLsSNngcI3RbjyR8NaUE6L1qzpWttoQ3/6TVukg7pPeIbEzy9gCUYETrFPL0r5Rbqhi/tEcYNpamLITo4li9q7FY6nnSFLmeePgBdX+bzsoiJZhE16tiZFqDEMzixQpvTikgY9lOgXawWJiZCs9q+yTiX2vfGQY42s/uiMT44n9unn8Cxetg3YTwYLb47C15hv+rPvbg47CeNc+kmCyElzjds47Ks/a82NSbXdMabIuNSDADYnKOd/guWBd3iH0lmt+oL61ChTrAgNTPRb6dtJqfYm29UKrojpL2MUv1UTTR8LclTyq/CN14CeQGZPGM8hhYW5GyarroVmUa734y5TkGxUpq72U8NM9XamK2pjl0P+2muSEYujvCVkimxW4ksQzXYw4xd1liHyxh1klA2zYThWoifayBaQgMtFchrTU2/haxNf6u1HAX4DpdCkqI02xgthh0XsTcet1YA1L0kO5ZTihvZZum5rNw/LrF19zBAwihkjfRXY=
after_success:
- codecov -t $CODECOV_TOKEN
