language: python
python:
- '3.6'
install:
- make install-tests
script:
- make tests
deploy:
  provider: heroku
  app: movexplo
  api_key:
    secure: btlBiL6/gq9eT58Z7aRWUygdGHH+UEmcqlL/TFqJOWR5djcRPeIJxTDOThhVCe2FS3u0WS0CHTxrSEsglpdW0D/EFaYur0RJos6kfrNtJsD2MYlbjesH19Wc236EG/2eBRqzcxMMVoH5+NjmhjkoNbsrOdKOmiOqRYI817gHtcnAQtJ8DTwu/14SESxRfAYVZ4bJnd4q+MYj1a77tKOFWXevFvWa8T92xVrNFnv1iGinSdBFS40IBaoW4kNBOmreBO8yNI7gRwCV3B/+bpZboXtnVY3OmBQAVINftZ6UNX5N6y7T/DtT+HcFZZ1DQ0f3le/uVFVcpZWBxUzFx8ktfK8kNeQxdi/QqMmIQKa7fkeCokCMbs1Vs+xAdjtlUwHohS33a/Ixxkr/eYMKDo2jIb1yykFh0GA6UhqIMOihG/rJQZpV2l7UodPqp1H4jxZkGTxvPAoRvlbSOEE/Jwe06Kr1zkuRDUstxXBOG34eYoo/Ez1dn6cAbv+LRGRA7R4bawQIfDG6Ud8Uk8Ps4P3DBC30LTWTG0O93KDISPM1KpJqwp80I+REXzx5ittFEOZNCCF/L4Nu/+WgJrfg2hLj5xX8Gf0IKgD56eB3Yo3285x25xjv4tWxM4o+k0ny+Y+34cL4d+4XfZM0RFpd/z3XHf7/pmSfz24F+koyGLDCIgg=
after_success:
- codecov -t $CODECOV_TOKEN
